---
- name: Execute Script on Web Servers and Create Checker File
  hosts: dev_db_group_2_A_nonITAR
  become: no

  tasks:
    - name: Check if the task has already been executed for this host
      shell: cat /edm/DONOTDELETE/ansible_linux_patching/stop_checker_file 2>/dev/null
      register: checker_file_content

    - name: Run the script if the task has not been executed
      block:
        - name: Run the script
          command: /edm/DONOTDELETE/ansible_linux_patching/stop_db_all_single_node.sh
          register: script_result
          ignore_errors: yes

        - name: Check for errors
          fail:
            msg: "Script execution failed with exit code {{ script_result.rc }}"
          when: script_result.rc != 0

        - name: Add hostname to the checker file on success
          lineinfile:
            path: /edm/DONOTDELETE/ansible_linux_patching/stop_checker_file
            line: "{{ inventory_hostname }}"
          when: script_result.rc == 0
      when: checker_file_content.stdout.find(inventory_hostname) == -1

    - name: Display checker file content
      shell: cat /edm/DONOTDELETE/ansible_linux_patching/stop_checker_file
      register: checker_file_content_after

    - name: Display checker file status
      debug:
        msg: "Checker file content: {{ checker_file_content_after.stdout }}"
